// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockState } from "./BlockState";

export type Block = { id: string, query: string, state: BlockState, result: string | null, };
