// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaceholderValue } from "./PlaceholderValue";

export type PasteResult = { name: string, values: Array<PlaceholderValue>, };
