// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
    surreal_endpoint: string;
    surreal_namespace: string;
    surreal_database: string;
    surreal_username: string;
    surreal_password: string;
    placeholder_prefix: string;
};
