// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suggestion } from "./Suggestion";

export type Suggestions = { placeholders: Array<Suggestion>, ids: Array<Suggestion>, schema: Array<Suggestion>, };
