// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { TaskParam } from "./TaskParam.ts";

export type TaskMeta = { name: string; params: Array<TaskParam> };
